Feature add amount to claim, add command transfer and also small refactor
atticwip/claimable-tokens pull request #1
Opened 2021-06-04 11:38 UTC by godcodehunter

2021-06-06 16:02 UTC, ysavchenko requested changes
I was a little nit-picky with this review, just to save us a lot of time in the future. Please see my comments below.

Also, make sure you run `cargo fmt` and `cargo clippy` when you finalize the code before the review.

2021-06-06 16:02 UTC, ysavchenko commented on cli/Cargo.toml
> +solana-cli-config = "1.5.0"
Use the latest lib versions (`1.6.9` as far as I can remember).

2021-06-06 16:02 UTC, ysavchenko commented on program/src/utils/program.rs
> +pub fn get_address_pair(mint: &Pubkey, eth_address: EthereumPubkey) -> Result<((Pubkey, u8), (Pubkey, String)), PubkeyError> {
This tuple-of-tuples seems a bit too much, if all these values are needed may be add a struct here with named fields?

2021-06-06 16:02 UTC, ysavchenko commented on program/src/instruction.rs
> +        AccountMeta::new(*fee_pair, true),
typo: `fee_payer`?

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +            let amount = value_t!(args.value_of("amount"), u64)
Change amount to be `f64` and convert it into `u64` according the the token precision.

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +            let amount = value_t!(args.value_of("amount"), u64)
Also use `f64` here, see above.

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +            let conv_eth_add: EthereumPubkey = ethereum_address.as_bytes().try_into().expect(
Please check if this verification works on the Ethereum address format used (with `0x` prefix), see here for the reference: https://etherscan.io/address/0xe61d6547ffa85ccac08bc337396a73efcc73add0

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +                    8,
Please add more descriptive errors here (like with example of the actual parameter), non-developers will be using this CLI. Also, does it really have to be length `8`?

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +                    "Incorrect ethereum address {}. Because len {}, but must be {}.",
Same here, see my comment about errors above.

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +                        .help("Mint witch token we send"),
`Mint for the token to send`

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +                    .help("Ethereum private key for sign transaction"),
`...to sign the transaction`

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +                        .help("Recipient ethereum address"),
`Ethereum` with capital `E`

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +                .help("Transfer different tokens to ethereum users account in solana network"),
`Transfer Solana token claimable by Ethereum users`

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +        signers.push(config.fee_payer.as_ref());
I think transaction should be signed by the `fee_payer` in any case (to pay the transaction fee)

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +    let ((_, _), (derive, _)) = get_address_pair(&mint, ethereum_address)?;
May be a little more descriptive variable name here (`holder_account`?)

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +    if let Response { value: None, .. } = config
I assume here you check if account already exists, right? This is hard to understand for the person reading the code (although a cool piece of Rust syntax :)). May be add a comment here explaining what you do.

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +    destination: Option<Pubkey>,
nit: I think `recipient` is a better name here.

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +    let eth_address = PublicKey::from_secret_key(&secret_key).serialize_compressed();
I do not think this will work. Solana uses a different cryptography, make sure you test this with actual Ethereum private/public keypairs.

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +    if destination.is_none() {
I think a better way to write this would be to unwrap `destination` to non-optional with assigning it to the associated token address if it was `None`.

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +    todo!()
Leftover `todo`

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +    println!("Transfer completed");
Please also print here the Solana address where the tokens were transferred.

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +            instructions.push(create_associated_token_account(
If you add this instruction then transaction should also be signed by the `owner`.

2021-06-06 16:02 UTC, ysavchenko commented on cli/Cargo.toml
> +libsecp256k1 = "0.3.5"
I do not see this dependency used in the code. Should it be removed?

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +                    .help("Mint for the token to send"),
`...token to claim`

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +                Arg::with_name("private_key")
Use CLI parameter name with dash instead of the underscore here (but keep the name with the underscore), like this: `with_name("private_key").long("private-key")`. This way you will still use the underscore in the code, but users will be entering dash.

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +                Arg::with_name("destination")
`recipient`

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +                    .help("Solana transfer destination account"),
`...recipient...`

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +                    .help("Amount to send"),
`...to claim`

2021-06-06 16:02 UTC, ysavchenko commented on cli/src/main.rs
> +            let pk_slice: [u8; 32] = private_key.as_bytes().try_into().expect(
nit: Fixed size array called `slice` :)

2021-06-06 16:02 UTC, ysavchenko commented on cli/Cargo.toml
> +authors = ["Atticlab team"]
You can keep yourself as the author, nothing wrong with some self-promotion. :)
If you use Attic, then it is better to write `Attic Lab`.

2021-06-07 10:07 UTC, godcodehunter commented on cli/src/main.rs
> +    let eth_address = PublicKey::from_secret_key(&secret_key).serialize_compressed();
There are used ecp256k1::PublicKey, so i think everything is ok with it.

2021-06-07 10:12 UTC, godcodehunter commented on cli/src/main.rs
> +            instructions.push(create_associated_token_account(
Hmm, strange, looked inside create_associated_token_account and only funding_address func param (argument &config.fee_payer.pubkey()) marked as signer

2021-06-07 14:28 UTC, godcodehunter commented on cli/Cargo.toml
> +libsecp256k1 = "0.3.5"
No, this is used in the code. For example, to parse a public key and get the corresponding private key.

2021-06-07 14:42 UTC, godcodehunter commented on cli/src/main.rs
> +                    8,
Could you please give more details how I could make this more user-friendly

2021-06-08 09:01 UTC, ysavchenko requested changes
Check my comments regarding converting params from strings to public/private keys.

2021-06-08 09:01 UTC, ysavchenko commented on program/src/utils/program.rs
> +pub type HashedEthereumPubkey = [u8; 20];
Better to rename it to address, if you hash pubkey on Ethereum and take the first 20 bytes you get an Ethereum address

2021-06-08 09:01 UTC, ysavchenko commented on cli/src/main.rs
> +            let conv_eth_pk = secp256k1::SecretKey::parse_slice(private_key.as_bytes())?;
Are you sure this is the right way to parse it? Private key is supposed to be in hex encoding (like this `112233445566778899aabbccddeeff00112233445566778899aabbccddeeff00`), it looks like the code above will turn it into 64 bytes instead of 32 bytes.

2021-06-08 09:01 UTC, ysavchenko commented on cli/src/main.rs
> +                secp256k1::PublicKey::parse_slice(ethereum_address.as_bytes(), None)?;
Same here, `ethereum_address` is supposed to be in the following format: `0x00112233445566778899aabbccddeeff00112233`, it looks like the code above will construct public key instead from the 42 bytes from characters in this string.

2021-06-08 14:37 UTC, merged